[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"

[context.production.environment]
  NODE_ENV = "production" 